export const ADD_DEVELOPER = "ADD_DEVELOPER";
export const RETRIEVE_DEVELOPERS = "RETRIEVE_DEVELOPRS";
export const UPDATE_DEVELOPER = "EDIT_DEVELOPER";
export const RETRIEVE_DEVELOPER_BY_ID = "RETRIEVE_DEVELOPER_BY_ID";
export const ADD_FEED = "ADD_FEED";
export const RETRIEVE_FEEDS = "RETRIEVE_FEEDS";
export const UPDATE_FEED = "UPDATE_FEED";
export const DELETE_FEED = "DELETE_FEED";
export const ADD_RESPONSE = "ADD_RESPONSE";
export const RETRIEVE_RESPONSES= "RETRIEVE_RESPONSES";
export const UPDATE_RESPONSE = "UPDATE_RESPONSE";
export const DELETE_RESPONSE = "DELETE_RESPONSE";

